### ISSUE TITLE
Allow input from stdin

### ISSUE THREAD

**Issue by mejo-** [PrivateBin/PrivateBin-Cli#3]
Great tool, I probably will use it a lot :)

Would be nice if one could pass content via stdin. Either by not giving a file name, or by giving `-` as file name.

**Comment by elrido** [comment]
Glad it is useful. Added both variants for reading from STDIN, no file name parameter or with a `-`. Usage message is now printed if the file or STDIN coun not be read or with `--help` or `-h`.

**Comment by mejo-** [comment]
Thanks a lot, works as expected :)
